common:
    azureShare:
        secret:
            content:
                azurestorageaccountname: ENC[AES256_GCM,data:Vxl99vx5SiPNSufyi6bNnYEZxvsMtgc=,iv:1I/7DAWi4s2TWlZeqIz2fQQ1mWduv4Tf8z5Aq0Eb+0Y=,tag:QEoG7/AeuoMd1V5Gfzl2Mw==,type:str]
                azurestorageaccountkey: ENC[AES256_GCM,data:JCzbKlbWrm7jzCa8Xy1vK3rGfso34HCw/v25hZrjHDKj6Kvk3PHp4kqgBm4rMKOzBYL/fy7P4IKA7JheEbd5v6GV1PPtcocqAOJP6CkqvwhsL57skd5U9g==,iv:QqkAMUnlyDMenEoVC0AyuzH6Vd7Q47R4sYJrp0aKK6g=,tag:+qQatidt/4wdvHnSoAXPvw==,type:str]
    config:
        sensitive:
            PG_PASSWORD: ENC[AES256_GCM,data:g22lNdn9RI6/zYT2g4C9XiPB,iv:PpKdfwAWeD4/eTndmlGVsiNV+UIdi44JSOFLrc/y7/A=,tag:Jo2AC/QAE2eiRhRANg5VZw==,type:str]
restore:
    config:
        sensitive:
            ADMIN_POSTGRES_PASSWORD: ENC[AES256_GCM,data:wGvnoSm6IB+HMAEg5kuhxySY,iv:ZOOZ/mRuJvw1WaqI0Ea5ksWiCG/UwgUACh2bT5DmG5c=,tag:HG1aKrCbOYu4jrZrlmmbmQ==,type:str]
            ADMIN_POSTGRES_USER: ENC[AES256_GCM,data:oLJvogy/ZSPsufc6DqjOEfs=,iv:I7E7ki/NW7sLMDxu0+8xWwq7dT1pJ9HNsVde66W67xM=,tag:jllVauKo0mNu8eUXKbiERg==,type:str]
            AZURE_TENANT_ID: ENC[AES256_GCM,data:vTKX9g5GCLSAJPuhZopguSrXM+t07TOB5vxTEqE3qkC1IX/q,iv:Kt3PCQwm8oIvTlw3f7KzHARH3Y+i/Mn4wVgOrdvt7fc=,tag:vMoPObALJPQJr5gHqf7dBA==,type:str]
            AZURE_CLIENT_ID: ENC[AES256_GCM,data:YIdWkZvZTz1teytYIXTuGTvyIpnAwOPZRr0r9VXPbz6EHHy6,iv:PB+VWJFKb0EoexO+XH0XYZh1LJKuYPbmKNCLCi2wOM4=,tag:xpCYWZIQ+OeFMUm0dbLQpQ==,type:str]
            AZURE_CLIENT_SECRET: ENC[AES256_GCM,data:H7/ZwL72b7bkXl2Kq75vyB0u02h+j4NrzM3p3dpdm6NLGZzWbSyg2A==,iv:3kYVJ0m+qAACyPEPi0xzX+aoJV8DLgSkjEaaqtMCkf0=,tag:/4ElTQdeBtG4PUEwdhA0yQ==,type:str]
sops:
    age:
        - recipient: age13da407hamk8c3rdp3nu3q8hqgxsefn902vrxsuphw2ljfmd2k5qqy7mgzx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcUJnUHRPbFgvMWZYWWFp
            ZWZzN2ZuSWRlODVpWTZhajRqUm9OM2JRODNBCnRYRGkzRDNrQWl3aHlTcnJzb2Iy
            SWtZazBTUjNVeXZoeVdpMUhxNXJkaDQKLS0tIEMxU0ZzOXIvdDdLd2xlQXF0S28r
            eWc3dDFsNlhNMmNQN3dVcjFReWVQaWcKuPUL7K9l9DJwYoecn28c/3dOVREIarx+
            dRjB5gi0Et1ZCSCWl8HV9NJR4Z0z1cz8RQxxdWbBtQtCOtmwLA4NAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWXpwTi9OZjV4VlN2NHpB
            NExrVDRnOGRXQXl4eGRMUzdsUDVKcmorWUdRClNQQzA0Ui92SkdDYWhzUTdIRHI2
            R0NaWkxTTVAzL3ZOSHA5a3BETURDaFkKLS0tIG5jajNPcnhEZ1dqcm9zZjMvTlQv
            WVd1UGhwMUUyM0R4SC9CTXBDMzE5MDQKBEyUbt/pOKxraUy/PI6rpTLhzif7De1a
            VpS0KuUGYb95sr7ooRyCZrP48Of4GvCoLoflwl5ynDO9kjkI+S77QA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w7q7xfuw2z4nshys80lt3l7y409rws4elevsqm74kh52a2g3pagqcfp9wq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbkZubnhUQmhuT3ZFcDFj
            SVpzRHRxS05TTmZjK0JNSDN6ZVJUZFQ1MGpvCmhGRWoxcFB2Q1c3ZGVieEJwbWV4
            eDZRcDhHckEwNFBEWVV0b3lOREZzNVUKLS0tIEZ4dmNkSU0wcTNGd0ttNTBKdlVr
            aHNCbVdCakV0KzVPZEtQUU5NWTFLUmMKCcJwKA6EirLnr+F3lLAVv1pyxSwHZAQK
            1UsfX2ATPAFHCgGw91cltQllb18Vngfsyt7X08c4LxNIPrXiF0J7lA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q22qgq5vyxatgxntpd8n7k0umqjvccny9ndf694f0kh3s76y5pnsc3386z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aHJ2M2o1ZGQvc2xmRWZu
            N20vMEs0UGpVcC9kQUNrY1dYa01iYnhSZHpVCk40N3IraW0xa1pHK01qN2NwMEQw
            dkM5eDZmZlhPT0xvRFowK2orQndEQzAKLS0tIG1hSGRINjllVEFyZUZRbmtCamQ4
            M1NyNEdXMEhISGNJSGZpMkdPeUpDUE0K5bIwEw936jqWz7gIDIWTIfAE31AchkhX
            yYskiUJGTwo9r431zRWc1e5/xOVdJDq5d59NeHqER8a0syfiy1JnRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OWYzd3drUDg5VWJZTXlo
            anRYS2RXQXJHQzF1UlJuT3ByUjM0aWhkVm1nCkNQSkR3QS9NVWk5MlYzVXBiektO
            RzlsK3lDYzZGN3J2UEovTmh3Y1dsU2MKLS0tIGx1bXMwUWM3RkFVNWd3VXg1UkJN
            YldsK240MU56cTV0TGNjWlR2YnB3aE0KR69nwKBoDcn9Cy07HcSAbeJrsC8LuSq9
            LB2vxMJ6sANwNGaiRUjvaogLzpZ2sDTqRUs9sW6zeuC/SLwIYRmB5w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeHlieFVWSFZuUGVsc0Rv
            VE4zZUVITEFvSUZSZ2twbHNTOStUc1FRL0FRCi9iVXRaU2VRdExJZ0d5cEREYUNI
            MVFxNWIvYXFZVGo3eUxQdys2akViZDgKLS0tIHk4MlVzM2psNFFHT2srOExIeW5p
            a0p5eXh3ejlha2JkalJmL1g3ekUyRjQKzluQURJMfxP37csa12lrvQEwxRQHvjT5
            6vLQAIc0Nd1lYDJ9POQqqag7xIFdIz1E+1YTUzr+oxsiiKXQYDdhlQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12y40q97r2ww94xt66u9uwvnt87a75d03tev7nj6dyrfugjsm9c5qr2te7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NTJEdlQwditWOXkvMTdE
            WFk4QjJ0RWVLS3M2R0NCd1dTY0xGR2FwWmhFCmJ0citsbVV4VnZxYU5qMWlSSVg2
            RDZpbHY3TFkyeXViQ1ZoY2F1S2hhVTAKLS0tIHZmQVpSK1hmbVJlNEp6UFR4ZFJX
            ZGlHUVZuWEsxM1lkUGNPdlFCaTFLUmcKrG1TYS9vfZkFBgaGqTOGE+mt4hE3gtZ8
            ajcxIuj4yyjRubCdaIKaXBfDTr+wi8z3HQzKCSYloTWZAlU8QDAdnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T15:31:23Z"
    mac: ENC[AES256_GCM,data:vf1+Pr1dY6VmkYwTPTt+YtKgCS3NC3Jk6Wrz1NkdZiIYHSSxVCAaXXYfOjMDKyK77jlp/1vPLBkqG/uqhe28y5dtOwvPKcQd473oMVkKcnyhI8F4ufrNATv1RpaUK7d5bz79HdNx09L30dDv9VoAk7EFIzrigB3nLCCO/Ui1ngE=,iv:H6jb5nw8ZyIiYfsDKl8Hf7/xmlC/CONaQSopr97gOtk=,tag:UsWjecnAkVls2PPu1i9mNg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
