common:
    azureShare:
        secret:
            content:
                azurestorageaccountname: ENC[AES256_GCM,data:Hj/cw+ejkDpokfLlCZ5R45MQS9rq,iv:wX2nuOfBf/EkaG46C1jQmxGpXQhwr1LkSUD8qfBHwT8=,tag:2erWBKuTfqzVhkYcd39sYQ==,type:str]
                azurestorageaccountkey: ENC[AES256_GCM,data:CviIWD9fKszUI9fRBbiPp5U5JzbCvcum5ORWHsWCbvzMNFDkcTErZp7gz2ytuQhUblEOi3VRw3FXH3fR3RLK6y2+fbR4gaa2xzazKiM4ohbJhIzN5L1/dg==,iv:aiiOgo+9oSTCeEt9i/yH4CSSDQW8VX9DeRZj0mesb1I=,tag:fbkqmn1An8ZDsm4s8mcEIw==,type:str]
    config:
        sensitive:
            PG_PASSWORD: ENC[AES256_GCM,data:kY2kqSa+UWOsetu0Cd/LkQSpRzhDLAbQ1I4cMvL/HhM=,iv:dJFVgkN4LP9jabtWOSzhytN1+vN9VYrj5F5apF5uUzU=,tag:xq5hN+S0FsK2RQVYFsbFBQ==,type:str]
            PRESSBOOKS_ALGOLIA_API_KEY: ENC[AES256_GCM,data:JL2IT+6IrGnKc7RkiUSzqK30CMNH3d+dMrBn92yElDQ=,iv:ypr3Esh0Q4Rc1526cw548H+CAkX+bXYmffmXsKruaNw=,tag:yg3PfPwTyf6agd32wKohHg==,type:str]
sops:
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabFY0VlZkaXhpV1lXaFJJ
            clNzSU9ZbFIyeERGajhpbjdnUkUxMklLT1JnCjNZOGJnZ21IRFhwaVh6TnV4K0ll
            QkozaDhWRFNxbkthL09zQ2JQdHFIQTQKLS0tIDNiMEFLZU9LRjdWVnhNZ1FmZDRm
            UFU0Uk5meW1xSXUrTzlmN0d4YTJra0UKAQaE8LAFWJ63DZIliV57WFGCsAaxnkgW
            dduBdIaj8O1ZDWd8qS/jU8IA426aeoKfT3Nn9slx7OX1EhzgIh4bbQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age195mrdujpg239kfgzq45je9fr7xsdnplt7etu35l0u8y6g67h3a3qxtzam2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaWZleWJ5OGltQUhYZSs5
            RmNKSzhhbU5xcW83NnpQV1o2MS93WktPdGhFCmY5TmFVR1FMRUJSc2hRWkRCb0dE
            N3JJU3BPcW83RysrUkhTOWtZUHpQaEUKLS0tIDNkcVJxdklTUi9yMmJQTVlNSE9G
            ZzV6SUJJRnFGTnQwckg1UERaa3ZOd3MKz9np7ujrK9T+xc8iehwn+ijTheKV/PG5
            PhARHE6BL1H7gjI7SmIVEHuno69taNYxwXZ3+9UQSMTOb9orXnUoYQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTXpCek1jZ3djV092NzBo
            MTdyN3k4dTIrSHVzT3pKRDEzWldGRXpHUldBCnJVSE8yK1ROaGY5WEhNK09WcVdW
            TUU2eHVzRzlwUnJ5VVF2ekdYbUVnTzQKLS0tIGZkeFhnMUQ3azltS0RUUGx3S3hJ
            NTFXMHJhVElGZFZFOENiVDlrOHJGQ1kKoVoI2JUzuGThEiGrCP0qcGYGtA4lYwon
            1BTkoPi+M0V2EIRmxiCk332aV0uksCGRWOxKkiaMcXhFi+GvwOkguQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kuagvmkjdw26q7dn9w5ljqd28ndrh4zvs38zepquftkn0ryyj97srw9gy4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeW5MRlhDYmNncHRtaGVo
            eTVyVE4wMTEvWUhmVG1wbUxrYkF1WW9vYUh3CjFvZWk4MzdzTjlIQ0QzYnRGQmxN
            Zm43eCtsc24rWksrandwMFVTa1FYWE0KLS0tIDVDV01HdERoVlA2ZlV6WmZlbWlB
            YkZzT2tSUzhFNDZRVktlQTh2QWVnbnMKPfs+i4ILdqSe2OyX1owW4d9P9J/1ocGF
            qgDoKADYN3TJu3bhSGQ8XJQfY6hSCnC4CTmx4P8fNwFNNuzJKCAWyQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidS9ScjZBcHRJeFRwV2hE
            MVlQWjVlbHRwYXpTaUt5VGJNeDNoQmpuUUhrCk9iK3JCL3c4ZC9SUDdMUTdoS2E3
            VW5Fazd6ZEg1eC9yajdtVFB2Z2UrcU0KLS0tIGJHRTFnc1VFMWlSMGFQcHRkNmU1
            RWFEOFBsN21zK3VNZWFSVlBneEdQbGMK+LjUI89vC/m2grvHMojvNWB+pRxYabGp
            JdQsgGhcuMYF8f2p1FlGRoOcTGU5IVlZsFyC8xU6kDuoGFy05Smx6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVVo1bC8xc2krbTZKNU9x
            MWlReGtYYmtBaVJ2NVZERGhXaHRlZmY1R0M0CkJDOEpjeFJtQTZSMHlnWjNWZFJE
            Mno4cmhiNU15STZTd2JhWHRLMVpWVncKLS0tIFBmVWZqQ0JtdjZVYzd2L1gybUMx
            VEJibk1GOE5kL1QzekJ4clRkTFQrVHcKxWsdF+jkT9nR+NutLP/7h6MjgExAevkV
            5JCjo/dtv6ZB8MVXOjWjjL49cXmCDJQI7E/lTT1DHJYBz7jZriU7Sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T14:02:59Z"
    mac: ENC[AES256_GCM,data:8l8cLkoFjCK9bhHDLeEdBCPRC+ruOiA22DftDjDMOYwNjDFI3AyRvZYLR8FpAgpR1edCaxeRwVyXajVoe/zKQBRl0YgXipXgsbObNnFXT7qxjPHyVVVf/9APYvZzSP9ARXIUb92eIwzu+mTxMfi3jBUkFR14hPj+KeQcMSXnnZw=,iv:L8YpG4Z2iLYOxyshFzhG+WPtFmeDd0Z/xZrvxBCjj+k=,tag:+L0OyhJCq9WIO4523XsoOg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
