common:
    azureShare:
        secret:
            content:
                azurestorageaccountname: ENC[AES256_GCM,data:dBTtz1XZJ40+pAyptl7hRqY6ivFE,iv:kJ3FxyGeYKM5cI6itPjrMhUPJNBn0uudX9tEXg/8O/s=,tag:fxOdZQB+c2GYA7Sh5K76tg==,type:str]
                azurestorageaccountkey: ENC[AES256_GCM,data:f7xcEBMyXMNmU0CXSaJWofqXjtB0S7+mPw6n+BcCkU5qSEnZ4FDh27I9JhyZNA7wink8rmdM/N8Y/eV2Qe9LJtidskEEolw23jz/VpjS9O8by2EZZK5LNQ==,iv:o88k4zfO0J+smZYqIW1Lj42Y4dOVeL+iAqYiIcqS9KU=,tag:Owd45Hh2196g9DAuGLdRmg==,type:str]
    config:
        sensitive:
            PG_PASSWORD: ENC[AES256_GCM,data:06JjhT3aotw9m66HHLTmfFp9b/uAfv8zofg9M8NA2LQ=,iv:KXNPq1XxPjA9xNNBjHP7HOAfa8aLeYuFE0sPk+KUwOA=,tag:wOdfFNjYxOFvQpg3jgBzxQ==,type:str]
sops:
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6KzRvdmVmcEhCVXcxUHlV
            TDRYN3lySTVNQUM2OGZjQnJBUW0rdzJpU0V3CitZWHpaQjJicHJxbmNlQUczZDZC
            WWZzSFBXZ1pVZE5EMjFkQjg0YmJlaTgKLS0tIGRTbzRtTzVyZlM2UW1aTkxJbG5T
            UUh2a2F2MUtPK0FHNDJ0bGRxRXRoYkkKmVpldWc1U86917Htu3uO7oesryj0xf6R
            Tb2F5QC6RR7tP1FiprFChAzPliG4/CeKrTVbcMFJ4giQrQzu7xMI4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WG1obHZwM3QvVlk1bDJr
            VEtYb2VmVXZ4YVZmRERYaDl4VlZoWUtUS1hjCnV1Q0dXUVpMNXBuZCszZmdGRXNa
            ZnNEd1NaZjR6VDVQWXh6YldjN1g2OWcKLS0tIGFPc2Z1OWJ2MmFoOWZSRXRWQTZy
            WmVDcENPTnhDZUNIMkNlSWY5RjJja28KcCKdw+heC0K81/BZTz4/0A5Ff2ggF9Mc
            IXGzKcjCv/RKV2NjxRUzOBmzUO64tQv3bL3aHrjChbudUWQDMusQGg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w7q7xfuw2z4nshys80lt3l7y409rws4elevsqm74kh52a2g3pagqcfp9wq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QkxzRXRaYTJUQzhLL2xH
            K25FdDdVRGJ1RDJweWdIcDI4R2dlbVF4WVcwCnhrVGdBek0vUTEwcHltR0w3RjRR
            VHozZUtGSnRya2t1cVVwWGozRTRGRW8KLS0tICtBdlpzSE15L1JDbVRHbElneThM
            NndZdElVWHdwVDY3UmlEUXdmMzRrL28KiY0OsPNDbQa1FDi6C+PVrjLEHIUozKnz
            2kJQatTh9xgotDrEinltkc+CbhK9kLUKt6x25TfICYlJh6/0Wtbs9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q22qgq5vyxatgxntpd8n7k0umqjvccny9ndf694f0kh3s76y5pnsc3386z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Q2UwVzFzbGFKTTA4bDFC
            UG1XMmtjaUwySDlVTFQ4UFhlQS9rS0RHZ0FNCmZGU1NIT09PSmJqSmdvcEFWL3lq
            dTR6Q05XQkNYVXVLQjk4MlZiVFIyZ1EKLS0tIC9VK21QaXg1RmVRR0FkQjUvOVFI
            YUFaSjAyNndHZFZwSUVaY1ZGUEVoQ2sKMqYqIDRfe1M64SLqjHZPRTSq6vLKz6of
            aufx2leUfYk7jyju/mV+lKCXkq5BCuP8SO+ImPPdHRoyXjVVueXbog==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQS9yZ3RrazB3MW55OEU5
            TWlsbWQyM0ZZaElHbS9XR0M2eS9BcjNNTm1jCkhMdytsdWV0bzVPNWZLWEhCUHlF
            aUtJclBweEljK1FBL3JYZnk0RHhObzgKLS0tIDY1SjdRV2E0N2M3MUNBK3lXdGRu
            eERlcEJwZXNpb25ZY3QzV2FFaFdPcFEKBNDdH79Q2nYHQBKdkvguJaNQXH99ww0b
            EMAbr86U/09naOaRt6K0wp97C2wnjLFN7w3Ylb0SfvTqCGXb8m3hnA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVyttYkoyQzBGcmlEaVNJ
            NE1BTUJVV3RseUo4eTZLYzlrNGtzY1pod2lrCi93bmF0LzBWc1doQTdwYkljMWVs
            cExLMkkyaFJQWGxIblpraUN2c0h6bGMKLS0tIFdncVRDa0U3VkxmUmg4alZES1FO
            RStxRmhRY0lHcFoyK3poYnZKVWNKVkEKlUKQKW6uUQpw8epGV5u4xSt5mwncGr4G
            1EbpCKVy4WhDuDDVN5jmR1mUYKjElXXE4UzHDiltK9qODciabsk60Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12y40q97r2ww94xt66u9uwvnt87a75d03tev7nj6dyrfugjsm9c5qr2te7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByODZLdTBIYjR3NFkxeHc5
            N1NmcE8vU3ZodXVMMVc4RFJYaS83aTdHeXhJCmUxM1U1VXJkNW1iU1JMZ1JNMlo3
            TlZYOFZyMi9NS3pXSnFvYTAwalYyWVEKLS0tIC9zdVRST3ZqcmhrbE5PclEyZHJa
            NmxwMkNGU3pIbnJOL2xjRDFham1sL3cKdlQaPkS2A/YlIY0bDkVpuDHP+GhKOKbA
            6KB49Jsf5Eq6WHiRiu8+o/UpWAPRqQZHcurmfv0oLBGHUrYUH7OG+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T15:30:31Z"
    mac: ENC[AES256_GCM,data:3v0Xq0IMZtdcWd2LfHhFpr2fpfkBSJBjHNeP4TJioOVuQeU38H9DohAw2WCAZS8ClFZ+TTKZh4fZMSjIQjQV78ZpdYGoL5xKsRQMEb+uM9pmSCmMMNa0X686xiB6iHUGmquwnzIbSfYkKnQY/xaHVISLC9B2YQ2xgtrDg0HdCk8=,iv:4eTPp0d7CR170R67eTJxxCpq9rDSf/QkC348esx+WGU=,tag:xmrXY1SFjv6pLJwcAIiG6g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
