common:
    azureShare:
        secret:
            content:
                azurestorageaccountname: ENC[AES256_GCM,data:E0uRye1DWs6wZa8o5PDNmwF0JDi+,iv:J8OSRNS3RS/d7e22lIUFwgvfR4nP8a6rgnUGmBQdb/0=,tag:AphtWfxgv54VFAUEdCsVAw==,type:str]
                azurestorageaccountkey: ENC[AES256_GCM,data:CE1U4/XmR43tRTReVfKDk6nNjDyxWW+729bpVTWrlHwIz6oB7LHLlOBf/SYhbY4Ua+h6R7GRfLmLh28a8X512OQIn0Uq+a3W+x4+LkCjuN8kqXUyd+QNCg==,iv:FGVTPpjXbBtiK2x9EBzBuMOg4faJ4gE1HXxm2jOgCRM=,tag:KW3SaHO176csBGgBjNjRaA==,type:str]
    config:
        sensitive:
            PG_PASSWORD: ENC[AES256_GCM,data:jhxf94ShAoT/vOz4pjcTKO9pzNjpWSodzJF0mzNslwQ=,iv:kgPpNsxnUPEUzjwzXAMN0e1Pcq0ED3rQkww37OYJIjo=,tag:c7oTJgBvKz+bYUPF5COETg==,type:str]
sops:
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeXFWd3gwcE9tTHdGTnpF
            RWtPc21CUG9CcS9kN242NDB0ZFZvcjJIclgwCmVSbDFiVXd2d3I4MnJINWFhVHNN
            ZEpQdk9hdWI2RTQreEFTaXNqT1BoOFkKLS0tIDF4T01ibG1CdWE2QnNlRWlwR2VK
            Qm1RQ1Urc3Z0YVB6cE0zbTJRZGxhZGMKY9jwI3T8T0CPP+CkTogTPpnlsvOCiMiC
            PtYmJ/7V5edb7dBix5S88/LQMljAR4YF8+6jQeDaKH1bQDdvVCwLeQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbC9pQmdBYldJQWo3RTky
            M0JpT3BzTy9abkhyTS9KM0VJY0J0QUdtekJFCmZCSWRRekcwaGRpekwwQmtUZU1l
            TGpmTE1tUzdscE84MDFyd1RFOVhqalkKLS0tIEVwbHFYb2RSL3lTVGhLWFN6MVBk
            VzBNNTVJbThIZUpZSVgzL1lINUw4ZjQKNA6Pqan5KuOD6dYe4eqasYNbSiZ6lLjJ
            WCM8EWPsjfUmIiTIuQBoPj72MeTNyeqWIFzoclQAZBUmyVxRuyMgNw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w7q7xfuw2z4nshys80lt3l7y409rws4elevsqm74kh52a2g3pagqcfp9wq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVGtsYUgvKys0S1RHUWhO
            SzZpbktYelZ0cE42blBucTN0QzZ5cWY1WWdrCnpiSlk3QnBTUDFiYk05R2NsV3lT
            L0JFQjVRcm5TNzlmZXN3ajhwZTZ3T2cKLS0tIFZqR1FjT29JRVJjS2FpdHJIczRz
            MmJ2RllpNjJza1Y0Mnc2YUY5VGlRcUEK4zYrO/F91Zlt4TO4bPRly5JlTmfz+OfI
            JxDwVldzML0wI2ER6DYUlq9RyHWtwjDUz+U4bFABS/mDY9IfumUAWQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q22qgq5vyxatgxntpd8n7k0umqjvccny9ndf694f0kh3s76y5pnsc3386z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUlNPb1NSTFpia0VUOHVr
            eGJmSVdNVnAxek5UdWppcWx0V3pkcUQyQUdzCkt5ajhDcTB0TGpuT3A0bEVCZ0Fo
            WDhkVFpPb3B0MFFDL1l6SjFpM3JPMmcKLS0tIGx6QktEd0c2QkFtaktQcytQZ29r
            YUxkc0tUZFFOY1IyYW1JTGJld0RnUWcKUCGq4ciKR2qbxtUrO2m6eQiB1MEo3pwi
            UxmbN1LQr6N3daLRdYAjEzfSHDCL9psjoGXGuzlNTDf5ITU31HYcJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQzRFRkxJOUZnT21MYWNB
            bnhkTWY5em56L2IxODVuOG02TFlxVmtDOVRVCmhibjlkU0xHd2tEWUNHWkdDcXRY
            RGFQRzAxUFZTczNkNS9WSjRJeVNMU1UKLS0tIFVHUk56Y2VkUTVXOWI0VGg0eGhO
            VjJFQndXbGxnSG1XSEp0R3RpNEpDTFkKg4S5WPUiCO9VCPu2OnWhjrT56/o70Ljf
            ZK6weUuPdHWdDP6VjTnt7Wb613g/5tsEdV5zygySiUpY3g80pWH4dw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTnlBN1lJK1d1dkFpd3g0
            L20xeHBCeWRzM3I3ZXJkeXFsRjd6aUEvdGk0Ci9xU2syK2tqbW9XTk50d1dRbkZP
            RCs0ZUpsKzdFaHFwR1plcnVURmVQVTgKLS0tIFJiQmN5NDdYcEdCN1pzQm51RXh1
            N2VtbUJHdnVMTTcvam5zdFo3eXNHdTQKRo25qF18ex/DH/mkSAkoFuWkzOnroRsS
            pzDn56/XF1H5Lx7DmWziUJ/eeRKhEV5HbSqPLc1RsSgfIOfQFb+K4g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age12y40q97r2ww94xt66u9uwvnt87a75d03tev7nj6dyrfugjsm9c5qr2te7k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvSVA4M0VNUUduZGxBWVJM
            VUhkV2dGaHZ5MVU5UjUwTklwMklMMDNRS2tVClFqT2VPMzhaaTM5QmJEV0JKbUN4
            ckFnNEJEQkt4bE9vQjdkSEYzMEV4K0UKLS0tIFdBckVJVnNVc0tITzZrUytUekd6
            ZkFqL0s5akorZ1p3SUM0dGh0cnBmS1kKNt8jzXlofbdt3bXF6KYxRI+FNGQN38Qb
            pFqxaqD8F3rImKC8huTyUYkY2a6bNirwYgjcitz2y0uEgDarcLWdkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T10:10:11Z"
    mac: ENC[AES256_GCM,data:GZyL05jYc6EgGMZz7xhponiZZ+v2mQLRjGkhJLq5187Mw/E6TEGKzaWXnY1Sb+XyMRQCAyQFH43jqk5XW/PHRZOhcELIGwEbFk4peC6CyLSJKYj1cR20SRYVoYikyTpGtmmwNi7TUURnCHJqU00aSmH5qolsy5yBRlWymglyv/k=,iv:e0CPlkOv62Hsk340mC6yBIMhcAo0tb4I813qL+FKriU=,tag:Lkllx2vhsOAgVkVxApxzTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
