common:
    azureShare:
        secret:
            content:
                azurestorageaccountname: ENC[AES256_GCM,data:E0uRye1DWs6wZa8o5PDNmwF0JDi+,iv:J8OSRNS3RS/d7e22lIUFwgvfR4nP8a6rgnUGmBQdb/0=,tag:AphtWfxgv54VFAUEdCsVAw==,type:str]
                azurestorageaccountkey: ENC[AES256_GCM,data:CE1U4/XmR43tRTReVfKDk6nNjDyxWW+729bpVTWrlHwIz6oB7LHLlOBf/SYhbY4Ua+h6R7GRfLmLh28a8X512OQIn0Uq+a3W+x4+LkCjuN8kqXUyd+QNCg==,iv:FGVTPpjXbBtiK2x9EBzBuMOg4faJ4gE1HXxm2jOgCRM=,tag:KW3SaHO176csBGgBjNjRaA==,type:str]
    config:
        sensitive:
            PG_PASSWORD: ENC[AES256_GCM,data:jhxf94ShAoT/vOz4pjcTKO9pzNjpWSodzJF0mzNslwQ=,iv:kgPpNsxnUPEUzjwzXAMN0e1Pcq0ED3rQkww37OYJIjo=,tag:c7oTJgBvKz+bYUPF5COETg==,type:str]
sops:
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJREdDMEg5eFdHdXB4bjBa
            SnpDb1E5VHF4UmVUSWtHMldZVzV5SFR3ZjJJClNwVkhzZW1rWWhzTDRIaXlvMEo2
            OW45c0dRdjZhTW5EZWcwV0hNNEdiYUUKLS0tIFZjcWtMaElYVEc3aHhZMkVMWjZ3
            VWNhMDZQOHA1K0FsMzJlWC9LbVBjdDAKDJBZ/ZP26cw5B8S9GKZhg59ciC5NVrAi
            lgralz9i+ISrFR3NDiI8MaBcf8n/BwRl0doivTjOdQ9b1UwwaIqWqg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NVZaYnV1S3lpVVVTVmc1
            ZDRjMDNsR2JCWjU3S2RVNWN4T2hCOUYyams4CnQwSVErT2luWmxFWTUxanpiVjAr
            RFA0ck9hZXFVcDJjck8zb1RvVXFZUmcKLS0tIFovb2szME5KS3pMSHBHS1FpVFJ1
            Z2NUVGNsNHEvTnNjVWZkNm8vWlZ4R2sKGSXLCsI4G4ZViImUL+h7krWB5cB3h9lh
            qHT542xI7X7n0b71DnmEkQOL3ocQezWp9u5lvaGrq2EkX92Z8mvR9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w7q7xfuw2z4nshys80lt3l7y409rws4elevsqm74kh52a2g3pagqcfp9wq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNFFVMTI3UzVJamRxTTVx
            akMvQ0pSanFHS2NJRGI4emk2Q3A1eG9GQkhvCnF2Z0xCTGp0alNsUWtTLzZHd2xz
            WEJkNjRrelVqTzc5ZFlNUG5wMGpmSHMKLS0tIFVIdXl2YXhkNTFsTzh1ejkwdits
            QTQ2QVN1dUFVcGVnaWY3Y0U4M0xtdlUKZiw32uDgU8cdhmxCyk4Ps+Opzu/dlJCY
            JJOXRDMkV7lbb2hCcQ4WTTvS2Pj8gnzAAKNl9c8PY0XzZfhJH9pXRA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q22qgq5vyxatgxntpd8n7k0umqjvccny9ndf694f0kh3s76y5pnsc3386z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaW1yRysvbEhoWGptdTVG
            eGpxeFlHNFNIMVhWYWVOTlFnaEdKY3JRZWxjCmhNV1FZSnN1M25QQ0hwM1NKcDVB
            SFVqSUhJQXVKZ0JRTWtFYnI1TEpYMEEKLS0tIHFoUzFONFlscnBrZDZpOEtBNWRK
            WkVNdmpaYVdSbm9aRXNXbi9jK3Q3V1EKK32YcS574nSPSPnJDuPLtT9VZoKZJQGB
            OJ2+Rks6VyPIl8d+efzmDcYnyo8Bx+gxy8equDhl6O9XHr+qW1SORQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ew6kcn0fa6faqkc8w2hg2ww7xrh2g87nwa7ncdc2eq6xf4vkfs5q8yxy0l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUUpaTVZjZ2psV1lDVVI5
            aVFkenFzbXVZdWYvU1NWL3I1R1JhUms1T0ZnCmlydnhScURERnpONzdQcGRrWWp1
            U1dlTUdMMXZOT3BYd0taLzVZK3RsNUUKLS0tIEtoUFNWZnBnZTBFZ3lhcHJHSG9x
            VFhhWkh6TG5KNytydHdHREVHOVBhSlEKs1DTGj6XdJMc9p8Jg2maKFhN95qEcrBQ
            KnmIhVO57ZU8x2N1dhuxEfcMQmYSe368+31ZD34iIAMqM0G7wuUHSg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1h2ta0vvj53zt9qyys5hskramd6cduy9k85hqaghjnrrrcv0e9shskl7dzd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSelF2SXE3andyQVdFUENC
            VHlwL0N1QWxlalZFTGVlV2lDaWhHRmNpT0hzCkhMTEF0ZXpDaHpwMUt4TmtUM1Mx
            NFQwdlpWTGxibGhuRWpLZmcrcUdvVVEKLS0tIDdNeG1YNkRoLzBKdFpIUmo5endV
            Q2lUWEw4emQrYUJDc2VNakJ6Mm8xSUUKZhFAHW9G0AFmwIkjpVhCW9+A/fq0GWrC
            KbOnDPMoE7dp5xj6kxO6bB+5O8G58z6jD+s6v6z1z7mxTES4UGyC3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T10:10:11Z"
    mac: ENC[AES256_GCM,data:GZyL05jYc6EgGMZz7xhponiZZ+v2mQLRjGkhJLq5187Mw/E6TEGKzaWXnY1Sb+XyMRQCAyQFH43jqk5XW/PHRZOhcELIGwEbFk4peC6CyLSJKYj1cR20SRYVoYikyTpGtmmwNi7TUURnCHJqU00aSmH5qolsy5yBRlWymglyv/k=,iv:e0CPlkOv62Hsk340mC6yBIMhcAo0tb4I813qL+FKriU=,tag:Lkllx2vhsOAgVkVxApxzTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
