common:
  environment: dev
  config:
    nonSensitive:
      PG_HOST: dev-lab-projects-backend.postgres.database.azure.com
      QDRANT_URL: '{{ .Values.common.qdrant_url }}'
      QDRANT_GRPC_PORT: '{{ .Values.common.config.qdrant_grpc_port }}'
      QDRANT_HTTP_PORT: '{{ .Values.common.config.qdrant_http_port }}'
      ENVIRONMENT: dev
    qdrant_grpc_port: 6334
    qdrant_http_port: 6333
    qdrant_url: http://qdrant-grpc.qdrant

cronWorkflows:
  enabled: true
