apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s.service-account-token" .Values.common.workflowRbac.serviceAccountName }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.common.workflowRbac.serviceAccountName }}
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.common.workflowRbac.serviceAccountName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.common.workflowRbac.serviceAccountName }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.common.workflowRbac.executorClusterRoleName}}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s.service-account-token" "artifact-gc" }}
  annotations:
    kubernetes.io/service-account.name: "artifact-gc"
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: artifact-gc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: artifact-gc
subjects:
- kind: ServiceAccount
  name: artifact-gc
roleRef:
  kind: ClusterRole
  name: artifact-gc
  apiGroup: rbac.authorization.k8s.io
