{{- with .Values.updateMaterializedViews }}
{{- $config := dict}}
{{- if $.Values.common.config }}
  {{- $_ := merge $config $.Values.common.config }}
{{- end }}
{{- if .config }}
  {{- $_ := merge $config .config }}
{{- end }}

{{- $commonLabels := dict }}
{{- if $.Values.common.commonLabels }}
  {{- $_ := merge $commonLabels $.Values.common.commonLabels }}
{{- end }}
{{- if .commonLabels }}
  {{- $_ := merge $commonLabels .commonLabels }}
{{- end }}

{{- $configGenerator := dict
"config" $config
"root" $
"commonLabels" $commonLabels
"name" .name }}

{{- include "common.config.resources" $configGenerator}}
{{- end }}
