{{- with .Values.updateMaterializedViews }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ .name }}-update-materialized-views
spec:
  entrypoint: update-materialized-views
  serviceAccountName: {{ $.Values.common.workflowRbac.serviceAccountName }}
  securityContext:
    {{- include "common.security.podSecurityContext.restricted" dict | nindent 4 }}
  templates:
    - name: update-materialized-views
      steps:
        - - name: refresh-qty-document-in-qdrant
            template: refresh-view
            arguments:
              parameters:
                - name: view_name
                  value: document_related.qty_document_in_qdrant
        - - name: refresh-qty-document-in-qdrant-per-corpus
            template: refresh-view
            arguments:
              parameters:
                - name: view_name
                  value: document_related.qty_document_in_qdrant_per_corpus
        - - name: refresh-qty-document-per-corpus
            template: refresh-view
            arguments:
              parameters:
                - name: view_name
                  value: document_related.qty_document_per_corpus

- name: refresh-view
      inputs:
        parameters:
          - name: view_name
      container:
      {{- with $.Values.image }}
        image: {{ tpl (printf "%s/%s:%s" .repository .path .tag) $ }}
      {{- end }}
        envFrom:
          - configMapRef:
              name: {{ .name }}
        args:
          - python
          - "-m"
          - welearn_datastack.nodes_workflow.UpdateMaterializedView.update_materialized_view
      volumeMounts:
        - name: secrets
          mountPath: "/secrets"
          readOnly: true

  volumes:
    - name: secrets
      secret:
        secretName: {{ .name }}
{{- end }}
