{{- with .Values.updateMaterializedViews }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ .name }}-update-materialized-views
spec:
  entrypoint: update-materialized-views
  serviceAccountName: {{ $.Values.common.workflowRbac.serviceAccountName }}
  securityContext:
    {{- include "common.security.podSecurityContext.restricted" dict | nindent 4 }}
  templates:
    - name: update-materialized-views
      steps:
        - - name: refresh-qty-document-in-qdrant
            template: refresh-view
            arguments:
              parameters:
                - name: view_name
                  value: document_related.qty_document_in_qdrant
        - - name: refresh-qty-document-in-qdrant-per-corpus
            template: refresh-view
            arguments:
              parameters:
                - name: view_name
                  value: document_related.qty_document_in_qdrant_per_corpus
        - - name: refresh-qty-document-per-corpus
            template: refresh-view
            arguments:
              parameters:
                - name: view_name
                  value: document_related.qty_document_per_corpus

    - name: refresh-view
      inputs:
        parameters:
          - name: view_name
      script:
        image: python:3.12-slim
        command: ["bash"]
        source: |
          #!/bin/bash
          set -e
          chmod +x /scripts/update-materialized-view
          /scripts/update-materialized-view "{{inputs.parameters.view_name}}"
      volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: secrets
          mountPath: "/secrets"
      envFrom:
        - configMapRef:
            name: {{ .name }}

  volumes:
    - name: secrets
      secret:
        secretName: {{ .name }}
    - name: scripts
      csi:
        driver: file.csi.azure.com
        readOnly: true
        volumeAttributes:
          secretName: {{ $.Values.common.azureShare.secret.name }}
          shareName: {{ $.Values.common.azureShare.name }}
{{- end }}
