{{- with .Values.updateMaterializedViews }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ .name }}
spec:
  entrypoint: refresh-view
  serviceAccountName: {{ $.Values.common.workflowRbac.serviceAccountName }}
  securityContext:
    {{- include "common.security.podSecurityContext.restricted" dict | nindent 4 }}
  templates:
    - name: refresh-view
      inputs:
        parameters:
          - name: view_name
      container:
      {{- with $.Values.image }}
        image: {{ tpl (printf "%s/%s:%s" .repository .path .tag) $ }}
      {{- end }}
        envFrom:
          - configMapRef:
              name: {{ .name }}
        args:
          - python
          - -m
          - welearn_datastack.nodes_workflow.UpdateMaterializedView.update_materialized_view
        volumeMounts:
        - name: secrets
          mountPath: "/secrets"
          readOnly: true
        env:
          - name: VIEW_NAME
            value: >-
            {{ print "{{inputs.parameters.view_name}}" }}

      volumes:
      - name: secrets
        secret:
          secretName: {{ .name }}
{{- end }}