name: Build image and push to registry
on:
  push:
    branches:
      - "**"
    tags:
      - "**"
      - "!**_deploy"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker:
    uses: CyberCRI/github-workflows/.github/workflows/build-push.yaml@main
    with:
      registry-name: ${{ vars.DOCKER_PROD_REGISTRY }}
      image-name: welearn-datastack
      image-tag: ${{ github.sha }}
      recursive-submodule-checkout: true
    secrets:
      submodules-app-private-key: ${{ secrets.INFRA_BOT_APP_PRIVATE_KEY }}
      submodules-app-id: ${{ secrets.INFRA_BOT_APP_ID }}
      submodules-app-installation-id: ${{ secrets.INFRA_BOT_APP_INSTALLATION_ID }}
      registry-username: ${{ secrets.DOCKER_PROD_USERNAME }}
      registry-password: ${{ secrets.DOCKER_PROD_PASSWORD }}
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml
    needs:
      - build-docker
  tag-deploy:
    needs:
      - lint-and-test
    uses: CyberCRI/github-workflows/.github/workflows/tag-deploy.yaml@main
  tag-deploy-fast:
    needs:
      - build-docker
    uses: CyberCRI/github-workflows/.github/workflows/tag-deploy-fast.yaml@main
