name: Lint & test
on:
  workflow_call:

jobs:
  tests:
    runs-on: wlds-lint-and-test-runner
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m pip install --no-cache-dir --upgrade -r ./requirements.txt
      - name: Check format
        run: make format-check
      - name: Lint
        run: make lint
      - name: Test
        run: make test
